version: 2.1

orbs:

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - build-demo

jobs:
  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn global add typescript
      - run: yarn compile
      - run: yarn lint

  build-demo:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/build/demo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./demo/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: cd demo && yarn install
      - save_cache:
          paths:
            - ./demo/node_modules
          key: v1-dependencies-{{ checksum "./demo/package.json" }}
      - run: yarn global add typescript
      - run: cd demo && yarn build
      - run: cd demo && yarn lint
