version: 2.1

orbs:

workflows:
  version: 2
  pipeline:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/build
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: sudo npm install -g typescript
      - run: npm run compile
      - run: npm run lint
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./demo/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: cd demo && npm install
      - save_cache:
          paths:
            - ./demo/node_modules
          key: v1-dependencies-{{ checksum "./demo/package.json" }}
      - run: cd demo && npm run build
